sudo: false
language: java
install: true
before_build:
mkdir lib/
wget -P "lib/" https://github.com/FRC2832/Robot_2019/raw/travis.ci/SparkMax-java-1.0.26.jar
script: ./gradlew build
after_success: ./gradlew bintrayUpload
jdk: oraclejdk9
